### ISSUE TITLE
导入Butterfly In China中，报了500错误

### ISSUE THREAD

**Issue by luboq** [virtadpt/exocortex-agents#1]
回去检查，发现只导入成功这4个：
Butterfly In China - Dangerous AQI day?
Butterfly In China - Hazardous AQI day?
Butterfly In China - Moderate AQI day? (2)
Butterfly In China - Unhealthy AQI day?

是我平台有问题么？导入时某个agent不正常？我用的10天前更新的Huginn

**Comment by virtadpt** [comment]
What error messages did you get for the other agents?

(你得到其他代理有什么错误信息？)

**Comment by luboq** [comment]
Thanks. I'm not sure if my huginn instance is aberrant, it's seems running normal now. 
but when import, get 500 error. Any clue to troubleshoot? 

BTW, My huginn version is that published about 10d ago, and import tripwire.json have no problem.
![gif](http://ww3.sinaimg.cn/large/d80a8e60gw1f0uuxa8640g20pw0gjkcs.gif)

**Comment by virtadpt** [comment]
Conferring with @cantino, this could be a bug in scenario import.  Please stand by.

**Comment by cantino** [comment]
Hello @waldens.  Would it be possible to see your Rails logs when this happens?

**Comment by luboq** [comment]
@cantino 

```
I, [2016-02-11T00:57:22.878269 #1389]  INFO -- : [aa953533-2ddc-4733-abaf-603cac030033] Started POST "/scenarios/scenario_imports" for 27.38.56.39 at 2016-02-11 00:57:22 -0500
I, [2016-02-11T00:57:22.879430 #1389]  INFO -- : [aa953533-2ddc-4733-abaf-603cac030033] Processing by ScenarioImportsController#create as HTML
I, [2016-02-11T00:57:22.880156 #1389]  INFO -- : [aa953533-2ddc-4733-abaf-603cac030033]   Parameters: {"utf8"=>"鉁, "authenticity_token"=>"VY8A8hQBlHfPWk4fHtluUFUOeIb/qpMyV/puginuvn2ZTZVcDcCP351mifF3TQg869KaPjdaxIK3w0WI4VQZrA==", "scenario_import"=>{"data"=>"{\r\n  \"schema_version\": 1,\r\n  \"name\": \"Butterfly in China\",\r\n  \"description\": \"Monitors weather forecasts and air conditions in places I go for work.\",\r\n  \"source_url\": false,\r\n  \"guid\": \"09ad0200d9e8c10f5ed8406ad9697640\",\r\n  \"tag_fg_color\": \"#ffffff\",\r\n  \"tag_bg_color\": \"#5bc0de\",\r\n  \"exported_at\": \"2015-12-28T07:37:30Z\",\r\n  \"agents\": [\r\n    {\r\n      \"type\": \"Agents::TriggerAgent\",\r\n      \"name\": \"Butterfly In China - Hazardous AQI day?\",\r\n      \"disabled\": false,\r\n      \"guid\": \"0db2a954f6a97eef625059cb868890ec\",\r\n      \"options\": {\r\n        \"expected_receive_period_in_days\": \"7\",\r\n        \"keep_event\": \"false\",\r\n        \"rules\": [\r\n          {\r\n            \"type\": \"field>value\",\r\n            \"value\": \"151\",\r\n            \"path\": \"aqi\"\r\n          },\r\n          {\r\n            \"type\": \"field<=value\",\r\n            \"value\": \"200\",\r\n            \"path\": \"aqi\"\r\n          }\r\n        ],\r\n        \"message\": \"Today's Air Quality forecast is {{ summary }} (actual AQI value: {{ aqi }}).  The AQI is hazardous today.  Have your inhaler on you.  Maybe you should stay home?\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::TriggerAgent\",\r\n      \"name\": \"Butterfly In China - Dangerous AQI day?\",\r\n      \"disabled\": false,\r\n      \"guid\": \"1a103e526768d84435e44404d00d30fa\",\r\n      \"options\": {\r\n        \"expected_receive_period_in_days\": \"7\",\r\n        \"keep_event\": \"false\",\r\n        \"rules\": [\r\n          {\r\n            \"type\": \"field>value\",\r\n            \"value\": \"201\",\r\n            \"path\": \"aqi\"\r\n          }\r\n        ],\r\n        \"message\": \"Today's Air Quality forecast is {{ summary }} (actual AQI value: {{ aqi }}).  The AQI is dangerous today.  Stay home, maybe wear a gas mask.  Don't bother going out.\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::TriggerAgent\",\r\n      \"name\": \"Butterfly In China - Unhealthy AQI day?\",\r\n      \"disabled\": false,\r\n      \"guid\": \"1b55eb20053b21f057c6518f32ce6a05\",\r\n      \"options\": {\r\n        \"expected_receive_period_in_days\": \"7\",\r\n        \"keep_event\": \"false\",\r\n        \"rules\": [\r\n          {\r\n            \"type\": \"field>value\",\r\n            \"value\": \"101\",\r\n            \"path\": \"aqi\"\r\n          },\r\n          {\r\n            \"type\": \"field<=value\",\r\n            \"value\": \"150\",\r\n            \"path\": \"aqi\"\r\n          }\r\n        ],\r\n        \"message\": \"Today's Air Quality forecast is {{ summary }} (actual AQI value: {{ aqi }}).  The AQI is unhealthy today, be extremely careful and have your inhaler on you.\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::TriggerAgent\",\r\n      \"name\": \"Butterfly In China - Moderate AQI day? (2)\",\r\n      \"disabled\": false,\r\n      \"guid\": \"2370497617b25db40142dedab3d6eb2a\",\r\n      \"options\": {\r\n        \"expected_receive_period_in_days\": \"7\",\r\n        \"keep_event\": \"false\",\r\n        \"rules\": [\r\n          {\r\n            \"type\": \"field>value\",\r\n            \"value\": \"50\",\r\n            \"path\": \"aqi\"\r\n          },\r\n          {\r\n            \"type\": \"field<=value\",\r\n            \"value\": \"100\",\r\n            \"path\": \"aqi\"\r\n          }\r\n        ],\r\n        \"message\": \"Today's Air Quality forecast is {{ summary }} (actual AQI value: {{ aqi }}).  The AQI is moderate today, be careful.\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::WeatherAgent\",\r\n      \"name\": \"Butterfly in China - Get Weather Forecast for Oakland, CA\",\r\n      \"disabled\": false,\r\n      \"guid\": \"2a9dba599df7feab63e81e6bb38edb49\",\r\n      \"options\": {\r\n        \"service\": \"wunderground\",\r\n        \"api_key\": \"{% credential weather_underground_api_key %}\",\r\n        \"location\": \"94607\",\r\n        \"which_day\": \"0\",\r\n        \"expected_update_period_in_days\": \"2\"\r\n      },\r\n      \"schedule\": \"6am\",\r\n      \"keep_events_for\": 604800\r\n    },\r\n    {\r\n      \"type\": \"Agents::EventFormattingAgent\",\r\n      \"name\": \"Butterfly in China - Build today's weather report for Oakland, CA\",\r\n      \"disabled\": false,\r\n      \"guid\": \"2d346b2aca03682e033e37649b305add\",\r\n      \"options\": {\r\n        \"instructions\": {\r\n          \"message\": \"Today's weather forecast for {{ location }} is {{ conditions }}, with a high of {{ high.fahrenheit }} degrees Fahrenheit and a low of {{ low.fahrenheit }} degrees Fahrenheit.  The average humidity for today will be {{ avehumidity }}%.\"\r\n        },\r\n        \"matchers\": [\r\n\r\n        ],\r\n        \"mode\": \"clean\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::EmailDigestAgent\",\r\n      \"name\": \"Butterfly in China - E-mail Vegas weather report\",\r\n      \"disabled\": false,\r\n      \"guid\": \"52f65edf0793d31c4fd6d71ffb38bfd8\",\r\n      \"options\": {\r\n        \"subject\": \"Today's DefCon weather report.\",\r\n        \"headline\": \"Here is your Las Vegas, NV weather report for today:\",\r\n        \"expected_receive_period_in_days\": \"2\"\r\n      },\r\n      \"schedule\": \"8am\",\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::TriggerAgent\",\r\n      \"name\": \"Butterfly In China - Hazardous AQI day? (2)\",\r\n      \"disabled\": false,\r\n      \"guid\": \"56b7a076842a80bca179a978ef138879\",\r\n      \"options\": {\r\n        \"expected_receive_period_in_days\": \"7\",\r\n        \"keep_event\": \"false\",\r\n        \"rules\": [\r\n          {\r\n            \"type\": \"field>value\",\r\n            \"value\": \"151\",\r\n            \"path\": \"aqi\"\r\n          },\r\n          {\r\n            \"type\": \"field<=value\",\r\n            \"value\": \"200\",\r\n            \"path\": \"aqi\"\r\n          }\r\n        ],\r\n        \"message\": \"Today's Air Quality forecast is {{ summary }} (actual AQI value: {{ aqi }}).  The AQI is hazardous today.  Have your inhaler on you.  Maybe you should stay home?\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::WeatherAgent\",\r\n      \"name\": \"Butterfly in China - Get Weather Forecast for Washington, DC\",\r\n      \"disabled\": true,\r\n      \"guid\": \"677832580e687b4d027c2b7630b60619\",\r\n      \"options\": {\r\n        \"service\": \"wunderground\",\r\n        \"api_key\": \"{% credential weather_underground_api_key %}\",\r\n        \"location\": \"20037\",\r\n        \"which_day\": \"0\",\r\n        \"expected_update_period_in_days\": \"2\"\r\n      },\r\n      \"schedule\": \"3am\",\r\n      \"keep_events_for\": 604800\r\n    },\r\n    {\r\n      \"type\": \"Agents::EmailDigestAgent\",\r\n      \"name\": \"Butterfly in China - E-mail weather report\",\r\n      \"disabled\": false,\r\n      \"guid\": \"77e2cf709a6c4a984f3f9e91294a1432\",\r\n      \"options\": {\r\n        \"subject\": \"Today's weather report.\",\r\n        \"headline\": \"Here is your weather report for today:\",\r\n        \"expected_receive_period_in_days\": \"2\"\r\n      },\r\n      \"schedule\": \"7am\",\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::TriggerAgent\",\r\n      \"name\": \"Butterfly In China - Unhealthy AQI day? (2)\",\r\n      \"disabled\": false,\r\n      \"guid\": \"8455f4b1c1cd5d459a9697c267c44e6c\",\r\n      \"options\": {\r\n        \"expected_receive_period_in_days\": \"7\",\r\n        \"keep_event\": \"false\",\r\n        \"rules\": [\r\n          {\r\n            \"type\": \"field>value\",\r\n            \"value\": \"101\",\r\n            \"path\": \"aqi\"\r\n          },\r\n          {\r\n            \"type\": \"field<=value\",\r\n            \"value\": \"150\",\r\n            \"path\": \"aqi\"\r\n          }\r\n        ],\r\n        \"message\": \"Today's Air Quality forecast is {{ summary }} (actual AQI value: {{ aqi }}).  The AQI is unhealthy today, be extremely careful and have your inhaler on you.\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::EventFormattingAgent\",\r\n      \"name\": \"Butterfly in China - Build today's AQI report for Oakland, CA\",\r\n      \"disabled\": false,\r\n      \"guid\": \"8d4f58dc24b36f927527113f56ce19f2\",\r\n      \"options\": {\r\n        \"instructions\": {\r\n          \"message\": \"{{ message }}\"\r\n        },\r\n        \"matchers\": [\r\n\r\n        ],\r\n        \"mode\": \"clean\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::WeatherAgent\",\r\n      \"name\": \"Butterfly in China - Get Weather Forecast for Las Vegas, NV\",\r\n      \"disabled\": true,\r\n      \"guid\": \"a62f4dde22f15723de053c7e9dbba7b6\",\r\n      \"options\": {\r\n        \"service\": \"wunderground\",\r\n        \"api_key\": \"{% credential weather_underground_api_key %}\",\r\n        \"location\": \"89109\",\r\n        \"which_day\": \"0\",\r\n        \"expected_update_period_in_days\": \"2\"\r\n      },\r\n      \"schedule\": \"7am\",\r\n      \"keep_events_for\": 604800\r\n    },\r\n    {\r\n      \"type\": \"Agents::WebsiteAgent\",\r\n      \"name\": \"Butterfly in China - Pull the AQI forecast for San Jose, CA\",\r\n      \"disabled\": true,\r\n      \"guid\": \"c0da2ba6d06d4e5797365a9e61feefe4\",\r\n      \"options\": {\r\n        \"expected_update_period_in_days\": \"7\",\r\n        \"url\": \"http://www.airnowapi.org/aq/forecast/zipCode/?format=application/json&zipCode=95119&distance=25&API_KEY={% credential airnow_api_key %}\",\r\n        \"type\": \"json\",\r\n        \"mode\": \"on_change\",\r\n        \"extract\": {\r\n          \"aqi\": {\r\n            \"path\": \"$.[0].AQI\"\r\n          },\r\n          \"summary\": {\r\n            \"path\": \"$.[0].Category.Name\"\r\n          }\r\n        }\r\n      },\r\n      \"schedule\": \"6am\",\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::EventFormattingAgent\",\r\n      \"name\": \"Butterfly in China - Build today's AQI report for San Jose, CA\",\r\n      \"disabled\": false,\r\n      \"guid\": \"c2c7852ff6b32adaf71234d784a13769\",\r\n      \"options\": {\r\n        \"instructions\": {\r\n          \"message\": \"{{ message }}\"\r\n        },\r\n        \"matchers\": [\r\n\r\n        ],\r\n        \"mode\": \"clean\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::EmailDigestAgent\",\r\n      \"name\": \"Butterfly in China - E-mail DC weather report\",\r\n      \"disabled\": false,\r\n      \"guid\": \"c454f4f908c190af716b7dd4f90c3663\",\r\n      \"options\": {\r\n        \"subject\": \"Today's DC weather report.\",\r\n        \"headline\": \"Here is your Washington, DC weather report for today:\",\r\n        \"expected_receive_period_in_days\": \"2\"\r\n      },\r\n      \"schedule\": \"4am\",\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::WebsiteAgent\",\r\n      \"name\": \"Butterfly in China - Pull the AQI forecast for Oakland, CA\",\r\n      \"disabled\": false,\r\n      \"guid\": \"cec988a8dc4ca545b320029331a6e1b4\",\r\n      \"options\": {\r\n        \"expected_update_period_in_days\": \"7\",\r\n        \"url\": \"http://www.airnowapi.org/aq/forecast/zipCode/?format=application/json&zipCode=94607&distance=25&API_KEY={% credential airnow_api_key %}\",\r\n        \"type\": \"json\",\r\n        \"mode\": \"on_change\",\r\n        \"extract\": {\r\n          \"aqi\": {\r\n            \"path\": \"$.[0].AQI\"\r\n          },\r\n          \"summary\": {\r\n            \"path\": \"$.[0].Category.Name\"\r\n          }\r\n        }\r\n      },\r\n      \"schedule\": \"6am\",\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::TriggerAgent\",\r\n      \"name\": \"Butterfly In China - Moderate AQI day?\",\r\n      \"disabled\": false,\r\n      \"guid\": \"db11c047567d385d034d73d1294a0a93\",\r\n      \"options\": {\r\n        \"expected_receive_period_in_days\": \"7\",\r\n        \"keep_event\": \"false\",\r\n        \"rules\": [\r\n          {\r\n            \"type\": \"field>value\",\r\n            \"value\": \"50\",\r\n            \"path\": \"aqi\"\r\n          },\r\n          {\r\n            \"type\": \"field<=value\",\r\n            \"value\": \"100\",\r\n            \"path\": \"aqi\"\r\n          }\r\n        ],\r\n        \"message\": \"Today's Air Quality forecast is {{ summary }} (actual AQI value: {{ aqi }}).  The AQI is moderate today, be careful.\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::EventFormattingAgent\",\r\n      \"name\": \"Butterfly in China - Build today's weather report for Las Vegas, NV\",\r\n      \"disabled\": false,\r\n      \"guid\": \"e4fe4b4614810f5bda34e43cb8d8a595\",\r\n      \"options\": {\r\n        \"instructions\": {\r\n          \"message\": \"Today's weather forecast for {{ location }} is {{ conditions }}, with a high of {{ high.fahrenheit }} degrees Fahrenheit and a low of {{ low.fahrenheit }} degrees Fahrenheit.  The average humidity for today will be {{ avehumidity }}%.\"\r\n        },\r\n        \"matchers\": [\r\n\r\n        ],\r\n        \"mode\": \"clean\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::TriggerAgent\",\r\n      \"name\": \"Butterfly In China - Dangerous AQI day? (2)\",\r\n      \"disabled\": false,\r\n      \"guid\": \"e7b49c848cd1cc14f177c1fe4fa7c0ed\",\r\n      \"options\": {\r\n        \"expected_receive_period_in_days\": \"7\",\r\n        \"keep_event\": \"false\",\r\n        \"rules\": [\r\n          {\r\n            \"type\": \"field>value\",\r\n            \"value\": \"201\",\r\n            \"path\": \"aqi\"\r\n          }\r\n        ],\r\n        \"message\": \"Today's Air Quality forecast is {{ summary }} (actual AQI value: {{ aqi }}).  The AQI is dangerous today.  Stay home, maybe wear a gas mask.  Don't bother going out.\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    },\r\n    {\r\n      \"type\": \"Agents::EventFormattingAgent\",\r\n      \"name\": \"Butterfly in China - Build today's weather report for Washington, DC\",\r\n      \"disabled\": false,\r\n      \"guid\": \"f4c0314fc14540eadf56b4e1cb5a59a7\",\r\n      \"options\": {\r\n        \"instructions\": {\r\n          \"message\": \"Today's weather forecast for {{ location }} is {{ conditions }}, with a high of {{ high.fahrenheit }} degrees Fahrenheit and a low of {{ low.fahrenheit }} degrees Fahrenheit.  The average humidity for today will be {{ avehumidity }}%.\"\r\n        },\r\n        \"matchers\": [\r\n\r\n        ],\r\n        \"mode\": \"clean\"\r\n      },\r\n      \"keep_events_for\": 604800,\r\n      \"propagate_immediately\": false\r\n    }\r\n  ],\r\n  \"links\": [\r\n    {\r\n      \"source\": 0,\r\n      \"receiver\": 11\r\n    },\r\n    {\r\n      \"source\": 1,\r\n      \"receiver\": 11\r\n    },\r\n    {\r\n      \"source\": 2,\r\n      \"receiver\": 11\r\n    },\r\n    {\r\n      \"source\": 3,\r\n      \"receiver\": 14\r\n    },\r\n    {\r\n      \"source\": 4,\r\n      \"receiver\": 5\r\n    },\r\n    {\r\n      \"source\": 5,\r\n      \"receiver\": 9\r\n    },\r\n    {\r\n      \"source\": 7,\r\n      \"receiver\": 14\r\n    },\r\n    {\r\n      \"source\": 8,\r\n      \"receiver\": 20\r\n    },\r\n    {\r\n      \"source\": 10,\r\n      \"receiver\": 14\r\n    },\r\n    {\r\n      \"source\": 11,\r\n      \"receiver\": 9\r\n    },\r\n    {\r\n      \"source\": 12,\r\n      \"receiver\": 18\r\n    },\r\n    {\r\n      \"source\": 13,\r\n      \"receiver\": 3\r\n    },\r\n    {\r\n      \"source\": 13,\r\n      \"receiver\": 10\r\n    },\r\n    {\r\n      \"source\": 13,\r\n      \"receiver\": 7\r\n    },\r\n    {\r\n      \"source\": 13,\r\n      \"receiver\": 19\r\n    },\r\n    {\r\n      \"source\": 16,\r\n      \"receiver\": 17\r\n    },\r\n    {\r\n      \"source\": 16,\r\n      \"receiver\": 2\r\n    },\r\n    {\r\n      \"source\": 16,\r\n      \"receiver\": 0\r\n    },\r\n    {\r\n      \"source\": 16,\r\n      \"receiver\": 1\r\n    },\r\n    {\r\n      \"source\": 17,\r\n      \"receiver\": 11\r\n    },\r\n    {\r\n      \"source\": 18,\r\n      \"receiver\": 6\r\n    },\r\n    {\r\n      \"source\": 19,\r\n      \"receiver\": 14\r\n    },\r\n    {\r\n      \"source\": 20,\r\n      \"receiver\": 15\r\n    }\r\n  ],\r\n  \"control_links\": [\r\n\r\n  ]\r\n}\r\n", "do_import"=>"1"}, "commit"=>"Finish Import"}
I, [2016-02-11T00:57:23.018392 #1389]  INFO -- : [aa953533-2ddc-4733-abaf-603cac030033] Completed 500 Internal Server Error in 138ms (ActiveRecord: 71.5ms)
F, [2016-02-11T00:57:23.019801 #1389] FATAL -- : [aa953533-2ddc-4733-abaf-603cac030033] 
RuntimeError (No user credential named 'weather_underground_api_key' defined):
  app/concerns/liquid_interpolatable.rb:303:in `render'
  app/concerns/liquid_interpolatable.rb:95:in `block in interpolate_string'
  app/concerns/liquid_interpolatable.rb:57:in `interpolate_with'
  app/concerns/liquid_interpolatable.rb:94:in `interpolate_string'
  app/concerns/liquid_interpolatable.rb:73:in `block in interpolate_options'
  app/concerns/liquid_interpolatable.rb:57:in `interpolate_with'
  app/concerns/liquid_interpolatable.rb:70:in `interpolate_options'
  app/concerns/liquid_interpolatable.rb:76:in `block (2 levels) in interpolate_options'
  app/concerns/liquid_interpolatable.rb:75:in `each'
  app/concerns/liquid_interpolatable.rb:75:in `each_with_object'
  app/concerns/liquid_interpolatable.rb:75:in `block in interpolate_options'
  app/concerns/liquid_interpolatable.rb:57:in `interpolate_with'
  app/concerns/liquid_interpolatable.rb:70:in `interpolate_options'
  app/concerns/liquid_interpolatable.rb:89:in `block in interpolated'
  app/concerns/liquid_interpolatable.rb:57:in `interpolate_with'
  app/concerns/liquid_interpolatable.rb:87:in `interpolated'
  app/models/agents/weather_agent.rb:84:in `weather_provider'
  app/models/agents/weather_agent.rb:96:in `validate_options'
  app/concerns/liquid_interpolatable.rb:11:in `valid?'
  app/concerns/dry_runnable.rb:51:in `save'
  app/models/scenario_import.rb:85:in `block in import'
  app/models/scenario_import.rb:74:in `map'
  app/models/scenario_import.rb:74:in `import'
  app/controllers/scenario_imports_controller.rb:10:in `create'
  config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'


I, [2016-02-11T00:57:32.790880 #1389]  INFO -- : [e4b7f1c8-132a-4d40-a419-4cc907b030bf] Started GET "/scenarios/" for 27.38.56.44 at 2016-02-11 00:57:32 -0500
I, [2016-02-11T00:57:32.792158 #1389]  INFO -- : [e4b7f1c8-132a-4d40-a419-4cc907b030bf] Processing by ScenariosController#index as HTML
I, [2016-02-11T00:57:32.803792 #1389]  INFO -- : [e4b7f1c8-132a-4d40-a419-4cc907b030bf]   Rendered scenarios/index.html.erb within layouts/application (8.4ms)
I, [2016-02-11T00:57:32.806348 #1389]  INFO -- : [e4b7f1c8-132a-4d40-a419-4cc907b030bf]   Rendered layouts/_navigation.html.erb (1.7ms)
I, [2016-02-11T00:57:32.806624 #1389]  INFO -- : [e4b7f1c8-132a-4d40-a419-4cc907b030bf]   Rendered layouts/_messages.html.erb (0.1ms)
I, [2016-02-11T00:57:32.806802 #1389]  INFO -- : [e4b7f1c8-132a-4d40-a419-4cc907b030bf]   Rendered application/_upgrade_warning.html.erb (0.0ms)
I, [2016-02-11T00:57:32.813203 #1389]  INFO -- : [e4b7f1c8-132a-4d40-a419-4cc907b030bf] Completed 200 OK in 21ms (Views: 15.9ms | ActiveRecord: 2.3ms)
```

**Comment by cantino** [comment]
Ah, there's the error.  @virtadpt references a credential called weather_underground_api_key, which you don't have.  I don't think this should be an exception, though.  @virtadpt, would you mind emailing me the scenario?

**Comment by virtadpt** [comment]
@cantino It's right here: https://github.com/virtadpt/exocortex-agents/blob/master/butterfly-in-china.json

@waldens I think I know what the problem is.  That scenario references an API key in the Credentials section of Huginn called {% credential weather_underground_api_key %} which should contain your API key for weatherunderground.com (please see http://blog.andrewcantino.com/blog/2014/01/12/never-forget-your-umbrella-again-with-huginn/ for more information).  It would seem that, if this credential doesn't exist the scenario won't import correctly.

I'm not entirely sure of how to fix this.  I should definitely fix my README.md file to mention this.  I don't think it's clear in the Scenario import that {% credentials %} have to be present before they'll import (I didn't even know this).

Thoughts, everyone?

**Comment by luboq** [comment]
After set weather_underground_api_key, the import is no problem. Thanks @virtadpt  @cantino !

**Comment by cantino** [comment]
Glad to hear it!  We should still not error on missing credentials, so I'll look into it.  @virtadpt, if you can send me the scenario when you have time, that'd be helpful.

**Comment by virtadpt** [comment]
@cantino The scenario in question is in this repository as butterfly-in-china.json.
